### ISSUE TITLE
Add me please

### ISSUE THREAD

**Issue by Duncmikw** [sakibulhasan/royale-heroes#1]
I am MKneumann please add me to the clash site

**Comment by sakibulhasan** [comment]
Hi, did not get what do u mean by adding u to the site? The site is open for everyone. Anyone who has the link can access the site :)

**Comment by Duncmikw** [comment]
Sorry, I was not fully understanding, all good I figured it out, very nice site, I bet you can charge for that.

Best Regards,
Mike Duncan
‭

**Comment by sakibulhasan** [comment]
Right now its just a fun project and I will try to keep it free as long as the server cost is not that much for me :)
