### ISSUE TITLE
Order clan member by name or rank

### ISSUE THREAD

**Issue by ninaincali** [sakibulhasan/royale-heroes#2]
Or anything else ;)

**Comment by sakibulhasan** [comment]
Thanks Nina ... Im on it :)

**Comment by sakibulhasan** [comment]
Its done ... check lemme know what do u think. :)

**Comment by ninaincali** [comment]
Love it! Now I think you should make money from that tool. Let me know if
you need help with that.



2018년 8월 24일 (금) 오전 12:25, Md Sakibul Hasan <notifications@github.com>님이 작성:

**Comment by sakibulhasan** [comment]
Thanks. Lemme know whats in ur mind? Im open to any interesing idea? How do u wanna help me?
